Update uygroa

diff --git a/uygroa b/uygroa
--- a/uygroa
+++ b/uygroa
@@ -14,44 +14,7 @@ local_rev=$(grep -oE 'Revision\s[0-9]{1,3}' "$0" | awk '{ print $2 }')
 online_rev=$(wget --no-check-certificate -q -O - "$update_base/$self" | grep -oE 'Revision\s[0-9]{1,3}' | awk '{print $2}')
 # END VARIABLES
 
-######### self-updater
 
-run_self_updater () {
-        logger -s -t uygroa-updater "Performing self-update to Version $online_rev."
-if      ! wget --quiet --output-document="$0.tmp" "$update_base/$self" ;
-then    logger -s -t uygroa-updater "Failed downloading new version!"
-        logger -s -t uygroa-updater "File requested: $update_base/$self"
-        exit 1
-fi
-OCTAL_MODE=$(stat -c '%a' "$0")
-    case ${OCTAL_MODE:--1} in
-        -[1] )          logger -s -t uygroa "Failed: Error : OCTAL_MODE was empty"; exit 1 ;;
-        777|775|755 )   logger -s -t uygroa "OCTAL mode set:${OCTAL_MODE}" ;;
-        * )             logger -s -t uygroa "Failed: Error in OCTAL_MODEs, found value=${OCTAL_MODE}" exit 1 ;;
-    esac
-if      ! chmod "$OCTAL_MODE" "$0".tmp ;
-then    logger -s -t uygroa-updater "Error on chmod $OCTAL_MODE %0.tmp from $update_base/$self, can't continue"
-        exit 1
-fi
-cat > /tmp/updatescript.sh << EOF
-#!/bin/sh
-if mv "$0.tmp" "$0";
-then    logger -s -t uygroa-updater "Update complete."
-        exec env update_self=0 /bin/sh "$0"
-        rm \$0
-else    logger -s -t uygroa-updater "Update failed."
-fi
-EOF
-        echo "Inserting update process..."
-            exec /bin/sh /tmp/updatescript.sh; rm /tmp/updatescript.sh
-}
-
-function_check_update () {
-if [ "${update_self}" -ne 0 ] && [ "${online_rev}" -gt "${local_rev}" ]
-then run_self_updater
-  else
-    logger -s -t uygroa "No update needed. You're running version $local_rev. The latest online version is $online_rev."
-fi }
 
 ######### uygroa
 
@@ -276,6 +239,45 @@ if grep -Fxq "addn-hosts=$path/ipv4_hosts" "$configuration"; then sed --in-place
 if grep -Fxq "addn-hosts=$path/ipv6_hosts" "$configuration"; then sed --in-place '/ipv6_hosts/d' "$configuration"; fi
 function_dnsmasq_restart
 }
+
+######### self-updater
+
+run_self_updater () {
+        logger -s -t uygroa-updater "Performing self-update to Version $online_rev."
+if      ! wget --quiet --output-document="$0.tmp" "$update_base/$self" ;
+then    logger -s -t uygroa-updater "Failed downloading new version!"
+        logger -s -t uygroa-updater "File requested: $update_base/$self"
+        exit 1
+fi
+OCTAL_MODE=$(stat -c '%a' "$0")
+    case ${OCTAL_MODE:--1} in
+        -[1] )          logger -s -t uygroa "Failed: Error : OCTAL_MODE was empty"; exit 1 ;;
+        777|775|755 )   logger -s -t uygroa "OCTAL mode set:${OCTAL_MODE}" ;;
+        * )             logger -s -t uygroa "Failed: Error in OCTAL_MODEs, found value=${OCTAL_MODE}" exit 1 ;;
+    esac
+if      ! chmod "$OCTAL_MODE" "$0".tmp ;
+then    logger -s -t uygroa-updater "Error on chmod $OCTAL_MODE %0.tmp from $update_base/$self, can't continue"
+        exit 1
+fi
+cat > /tmp/updatescript.sh << EOF
+#!/bin/sh
+if mv "$0.tmp" "$0";
+then    logger -s -t uygroa-updater "Update complete."
+        exec env update_self=0 /bin/sh "$0"
+        rm \$0
+else    logger -s -t uygroa-updater "Update failed."
+fi
+EOF
+        echo "Inserting update process..."
+            exec /bin/sh /tmp/updatescript.sh; rm /tmp/updatescript.sh
+}
+
+function_check_update () {
+if [ "${update_self}" -ne 0 ] && [ "${online_rev}" -gt "${local_rev}" ]
+then run_self_updater
+  else
+    logger -s -t uygroa "No update needed. You're running version $local_rev. The latest online version is $online_rev."
+fi }
 
 
 option="${1}"
